# -*- coding: mbcs -*-
#
# Abaqus/CAE Release 2018 replay file
# Internal Version: 2017_11_07-11.21.41 127140
# Run by sebastian.chirinos on Mon Oct 12 20:22:37 2020
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=79.6100006103516, 
    height=120.839996337891)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from caeModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
execfile('CrossAsymmetric_Analysis_AttributeSpace.py', __main__.__dict__)
#: The model database "C:\Users\sebastian.chirinos\MEEN 491H\Substructures\CrossAsymmetric\CrossAsymmetric.cae" has been opened.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
#: A new model database has been created.
#: The model "Model-1" has been created.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
#: The model database "C:\Users\sebastian.chirinos\MEEN 491H\Substructures\CrossAsymmetric\CrossAsymmetric.cae" has been opened.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
#: Warning: Mesh deleted in 11 regions due to geometry association failure.
#: The model "Substructure_Model" has been created.
#* KeyError: CrossAsymmetric
#* File "CrossAsymmetric_Analysis_AttributeSpace.py", line 811, in <module>
#*     substructureModel(modelData,i=counter,matricesFile = 'MATRICES')
#* File "CrossAsymmetric_Analysis_AttributeSpace.py", line 693, in 
#* substructureModel
#*     p = mdb.models[modelName_Sub].parts[partName]
